- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: installing apache
      yum:
        name: httpd
        state: present

    - name: install java
      service:
        name: httpd
        state: started
